language: csharp
solution: EnigmaBinary.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore EnigmaBinary.sln
after_script:
  - nunit-console EnigmaBinaryTest/bin/Debug/EnigmaBinaryTest.dll
    - .\packages\OpenCover.4.6.519\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\EnigmaBinaryTest\bin\Debug\EnigmaBinaryTest.dll" -filter:"+[EnigmaBinaryTest]*  -[EnigmaBinaryTest]EnigmaBinaryTest.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\EnigmaBinaryTest_coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "EnigmaBinaryTest_coverage.xml
    - bash <(curl -s https://codecov.io/bash)
